server:
  port: 8080

spring:
  application:
    name: producer-app

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Producer Application
    description: Payment service producer
    version: 1.0.0