server:
  port: 8081

spring:
  application:
    name: consumer-app

producer:
  service:
    url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Consumer Application
    description: Payment service consumer
    version: 1.0.0