server:
  port: 8081

spring:
  application:
    name: consumer-app
  jmx:
    enabled: true

producer:
  service:
    url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    jmx:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  server:
    port: 9002

com.sun.management.jmxremote:
  port: 9002
  rmi.port: 9002
  authenticate: false
  ssl: false

info:
  app:
    name: Consumer Application
    description: Payment service consumer
    version: 1.0.0